# Generated by Django 3.2.9 on 2021-11-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_agreement', models.BooleanField(null=True)),
                ('private_agreement', models.BooleanField(null=True)),
                ('geoLocation_agreement', models.BooleanField(null=True)),
                ('provide_third_parties_agreement', models.BooleanField(null=True)),
                ('marketing_agreement', models.BooleanField(blank=True, null=True)),
                ('email_marketing_agreement', models.BooleanField(blank=True, null=True)),
                ('sms_agreement', models.BooleanField(blank=True, null=True)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
