# Generated by Django 3.2.9 on 2021-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='get_time',
            field=models.IntegerField(null=True),
        ),
    ]
