# Generated by Django 3.2.9 on 2021-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_router_get_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='max_time',
            field=models.IntegerField(choices=[(30, '30분'), (60, '1시간'), (90, '1시간 30분'), (120, '2시간'), (150, '2시간 30분'), (180, '3시간'), (210, '3시간 30분'), (240, '4시간')]),
        ),
    ]
