# Generated by Django 3.2.9 on 2021-11-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_alter_router_max_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='get_time',
            field=models.IntegerField(choices=[(5, '5분'), (10, '10분'), (15, '15분'), (20, '20분'), (25, '25분'), (30, '30분')], null=True),
        ),
    ]
