# Generated by Django 3.2.9 on 2021-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_alter_agreement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='email_marketing_agreement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='geoLocation_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='marketing_agreement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='private_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='provide_third_parties_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='sms_agreement',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='term_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
