# Generated by Django 3.2.9 on 2021-11-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_alter_router_get_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='get_time',
            field=models.IntegerField(default=0),
        ),
    ]
