# Generated by Django 3.2.9 on 2021-11-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='max_time',
            field=models.IntegerField(),
        ),
    ]
