# Generated by Django 3.2.9 on 2021-11-29 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20211129_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
