# Generated by Django 3.2.9 on 2021-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='english',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
