# Generated by Django 3.2.9 on 2021-11-19 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0003_alter_quiz_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20)),
                ('sentence1', models.CharField(blank=True, max_length=500)),
                ('sentence2', models.CharField(blank=True, max_length=500)),
                ('sentence3', models.CharField(blank=True, max_length=500)),
                ('sentence4', models.CharField(blank=True, max_length=500)),
                ('sentence5', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
