# Generated by Django 3.2.9 on 2021-11-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
