# Generated by Django 3.2.9 on 2021-11-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_useranswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='voca1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='voca2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='voca3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='voca4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='voca5',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
